// Regenerates THIRD-PARTY-NOTICES.md from the dependency tree that actually ships.
// Run:  node scripts/make-notices.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const readPkg = d => { try { return JSON.parse(fs.readFileSync(path.join(d, 'package.json'), 'utf8')) } catch { return null } }
const resolveDep = (name, from) => {
  let dir = from
  for (;;) {
    const c = path.join(dir, 'node_modules', name)
    if (fs.existsSync(c)) return c
    const up = path.dirname(dir)
    if (up === dir) return null
    dir = up
  }
}

const seen = new Map()
const walk = (name, from) => {
  const dir = resolveDep(name, from)
  if (!dir) return
  const pkg = readPkg(dir)
  if (!pkg) return
  const key = `${pkg.name}@${pkg.version}`
  if (seen.has(key)) return
  const raw = pkg.license || (Array.isArray(pkg.licenses) && pkg.licenses[0]?.type) || 'see package'
  seen.set(key, { name: pkg.name, version: pkg.version, license: typeof raw === 'string' ? raw : JSON.stringify(raw) })
  for (const d of Object.keys(pkg.dependencies || {})) walk(d, dir)
}

const app = readPkg(ROOT)
for (const d of Object.keys(app.dependencies || {})) walk(d, ROOT)
const deps = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name))
const counts = {}
for (const d of deps) counts[d.license] = (counts[d.license] || 0) + 1

const out = `# Third-party notices

VidHelm itself is MIT licensed (see [LICENSE](LICENSE)). It ships and builds on the work below,
and this file is the notice those licences ask for. Generated by \`node scripts/make-notices.mjs\`
from the dependency tree that is actually packaged, regenerate it whenever dependencies change.

## FFmpeg and FFprobe - GPL-3.0-or-later

The installer bundles prebuilt \`ffmpeg.exe\` and \`ffprobe.exe\` (the gyan.dev "essentials" build,
configured with \`--enable-gpl --enable-version3\`), which do all decoding, rendering, analysis and
sound synthesis. They include GPL-licensed components such as x264, x265, Xvid, vidstab and
rubberband, so **those binaries are covered by the GNU General Public License v3 or later**, not by
VidHelm's MIT licence.

- Licence text: <https://www.gnu.org/licenses/gpl-3.0.html>
- Project and source: <https://ffmpeg.org/> · <https://git.ffmpeg.org/ffmpeg.git>
- The exact build VidHelm ships, with its own licence and build notes: <https://www.gyan.dev/ffmpeg/builds/>

VidHelm runs FFmpeg as a separate program over its command line rather than linking to it, and the
application's own source stays MIT. If you redistribute VidHelm, you carry the GPL obligations for
the FFmpeg binaries with it: pass this notice along, and be able to supply the corresponding source
for the exact build (the gyan.dev pages above host both).

## Electron and Chromium

The desktop shell is [Electron](https://www.electronjs.org/) (MIT), which embeds Chromium
(BSD-3-Clause plus the licences catalogued by the project) and Node.js (MIT). Installed builds
include \`LICENSE.electron.txt\` and \`LICENSES.chromium.html\` beside the executable.

## Fonts

The interface asks for [Inter](https://rsms.me/inter/) (SIL Open Font License 1.1) through Google
Fonts and falls back to the system UI font when it is unavailable.

## Models

Captions and script drafting run [Whisper](https://github.com/openai/whisper) (MIT) on your machine
through \`@huggingface/transformers\`; the weights download on first use rather than shipping with
the app.

## Optional extras (not bundled)

You install these yourself, and their terms are their own:

- [audio.cpp](https://github.com/0xShug0/audio.cpp) - Apache-2.0. Local voice cloning and audio generation.
- XTTS-v2 by Coqui: **CPML, non-commercial**. Fine for personal projects; prefer an Apache-licensed model for monetised video.
- [Adversal](https://adversal.ai), third-party video-analysis service for your assistant.

## npm dependencies

${deps.length} packages ship inside the application bundle: ${Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([l, c]) => `${c} × ${l}`).join(', ')}.
Each remains under its own licence, and the full text of each is in that package's folder inside
the app bundle (\`resources/app.asar\`) and in \`node_modules/\` when building from source.

| Package | Version | Licence |
|---|---|---|
${deps.map(d => `| ${d.name} | ${d.version} | ${d.license} |`).join('\n')}
`

fs.writeFileSync(path.join(ROOT, 'THIRD-PARTY-NOTICES.md'), out, 'utf8')
console.log(`THIRD-PARTY-NOTICES.md written - ${deps.length} packages`)
