#!/usr/bin/env node
// VidHelm MCP server, lets Claude (Code / Desktop) drive a running VidHelm instance.
// Zero dependencies: speaks MCP JSON-RPC over stdio and proxies to the app's localhost
// agent bridge (electron/main.ts, default http://127.0.0.1:5959). See docs/AGENT.md.
import http from 'node:http'
import readline from 'node:readline'

const BRIDGE = `http://127.0.0.1:${process.env.VH_AGENT_PORT || 5959}`
const NOT_RUNNING = 'VidHelm is not running. Start it first: `npm run dev` (or launch the installed app), then retry.'

// How long to wait for each command comes from agent/timeouts.mjs, the same table the app's
// bridge uses, plus a margin so the bridge's own (clearer) timeout message always arrives first.
// A copy of this file on its own still works: it then waits as long as the longest bridge
// timeout and lets the app enforce the real limit.
let proxyTimeoutMs = () => 4 * 60 * 60 * 1000 + 60 * 1000
try { ({ proxyTimeoutMs } = await import('./timeouts.mjs')) } catch { /* standalone copy: keep the ceiling */ }

const call = (method, path, body) => new Promise((resolve) => {
  const timeout = proxyTimeoutMs(method === 'POST' ? body : { action: path === '/state' ? 'get_state' : path.slice(1) })
  const req = http.request(`${BRIDGE}${path}`, { method, headers: { 'Content-Type': 'application/json' }, timeout }, res => {
    const chunks = []
    res.on('data', c => chunks.push(c))
    res.on('end', () => {
      const buf = Buffer.concat(chunks)
      if (res.headers['content-type']?.includes('image/png')) return resolve({ png: buf })
      try { resolve(JSON.parse(buf.toString() || '{}')) } catch { resolve({ error: 'bad response from app' }) }
    })
  })
  req.on('error', () => resolve({ error: NOT_RUNNING }))
  req.on('timeout', () => { req.destroy(); resolve({ error: 'app timed out: the command may still be running in VidHelm, so call get_state before retrying it', stillRunning: true }) })
  if (body) req.write(JSON.stringify(body))
  req.end()
})

// Sent to the client on connect. Users who installed the app have no repo (so no CLAUDE.md
// or AGENTS.md), this is how a fresh assistant learns the working style anyway.
const INSTRUCTIONS = `VidHelm is a desktop video editor the human is watching while you drive it. Your edits appear in their window instantly, and they can move things between your calls.

How to work:
1. Call get_state first, and again after they have touched anything, never assume the timeline.
2. Make a few edits, then screenshot to see what they see. Report what happened in plain language; they cannot see your tool calls.
3. Tag points are the shared language: they press M at beats that matter. Hang SFX, text and narration on tag times from get_state rather than hardcoded numbers.
4. get_state.startRecipe is their standing workflow ("#" = a disabled line). "Run my workflow" means call run_recipe for the app-native steps, then do the lines meant for you: pitch title options in chat, propose a thumbnail subtitle, then compose_thumbnail.
5. export_video blocks until rendered and returns a quality check (loudness, peaks, black frames), relay that verdict.
6. Tracks: v1 video, v2 b-roll (picture only, sits over v1), a1 voice/music, a2 sound effects. Times are seconds; text x/y are 0-1 of the frame.
7. Ask before destructive edits (deleting their clips, exporting over an existing file). Prefer adding to rearranging.

Handy: cut_pauses strips dead air; set_booth_script writes a read-along script into the karaoke booth for a clean one-take re-record; open_panel model3d {path} loads an STL/3MF/OBJ/GLB and render_3d turns it into a spinning clip (transparent + still gives an alpha PNG that overlays footage).

Looks: when they describe a style ("make it fun", "clean minimalism", "futuristic tech captions", "cartoon"), call set_theme with their words. It lands on a finished baseline theme (captions, titles and thumbnail text together) and their tweak rides on top ("but blue", "bigger", "at the top"). make_captions transcribes on-device and captions the timeline in the theme. Lean music, SFX and transitions toward the theme's "feel".

Thumbnails: real pictures win on this channel. compose_thumbnail uses the creator's own photo when the project has one (thumb.jpg / cover / photo), else the best REAL frame (sample_frames rank:true shows the shortlist; look at them), else a placeholder. When the result has tellTheCreator, say it: ask them for a real photo.

Cutting to a spoken line: never read a timestamp off a transcript and use it. find_phrase and cut_at_phrase end on the last word of the THOUGHT and drop whatever trails after it, then snap to the waveform, so you get "...espresso maker" rather than "...espresso maker and this".

B-roll: scan_broll measures a folder and gives you a contact sheet per clip. LOOK at each sheet and label_broll what is in it; those labels are all plan_broll has to match against. Then plan_broll (nothing moves yet), read it, and place_broll commits it to v2. Cutaways are picture only, so the audio runs straight through underneath.

Vertical crops: plan_framing measures where the subject is and returns steady holds plus a proof sheet with the crop drawn on each one. Open the proof: detail and motion find the biggest busy object, which is not always the subject, and you fix that with hints rather than trusting the numbers.

If a reply carries stillRunning, that command is still going inside the app (a long render, a Whisper pass, a paid AI clip): call get_state to see whether it landed instead of sending it again.

If a tool says VidHelm is not running, the app is closed, ask them to open it. If they cannot connect at all, tell them to click the robot "AI" button in VidHelm's header for live diagnostics.`

const num = { type: 'number' }, str = { type: 'string' }, bool = { type: 'boolean' }
const TOOLS = [
  { name: 'get_state', description: 'Full editor state: format, duration, playhead, media bin, clips (all tracks), texts, and tag points, plus project (the open project or file name) and unsaved (true while there are changes not saved yet). A media bin entry with offline:true points at a file that is missing: the human relinks it in the Media panel. Call this first and after batches of edits.', inputSchema: { type: 'object', properties: {} } },
  { name: 'screenshot', description: 'PNG screenshot of the VidHelm window, see what the human sees.', inputSchema: { type: 'object', properties: {} } },
  { name: 'add_media', description: 'Import a video/audio/image file by absolute path into the media bin, and (by default) append it to the timeline. chromaKey marks it as green-screen footage: that colour is removed on export and in the preview so the clip underneath shows through.', inputSchema: { type: 'object', properties: { path: str, place: { ...bool, description: 'false = bin only' }, start: { ...num, description: 'explicit timeline position (s)' }, chromaKey: { ...str, description: 'hex key colour to remove, e.g. #00e800' } }, required: ['path'] } },
  { name: 'add_clip', description: 'Place an already-imported media item on the timeline. media = bin item name (fuzzy) or id. track: v1=video, v2=b-roll (picture only, sits over v1), a1=voice/music, a2=sfx. Pictures go on v1/v2 and sound on a1/a2; anything else is refused.', inputSchema: { type: 'object', properties: { media: str, track: { ...str, enum: ['v1', 'v2', 'a1', 'a2'] }, start: num, duration: num, sourceStart: num, volume: num, fadeIn: num, fadeOut: num }, required: ['media'] } },
  { name: 'update_clip', description: 'Patch a clip (by clipId from get_state): start, duration, sourceStart, volume, fadeIn, fadeOut, trackId.', inputSchema: { type: 'object', properties: { clipId: str, start: num, duration: num, sourceStart: num, volume: num, fadeIn: num, fadeOut: num, trackId: str }, required: ['clipId'] } },
  { name: 'split_clip', description: 'Split a clip at timeline time t (seconds), or where a word is spoken with at.', inputSchema: { type: 'object', properties: { clipId: str, t: num, at: { ...str, description: 'WORD ANCHOR: place it when these words are spoken instead of at a number, e.g. "arcade" or "end:arcade" (after/before pick between repeats)' }, after: num, before: num }, required: ['clipId'] } },
  { name: 'delete_item', description: 'Delete a clip, text, or tag by id.', inputSchema: { type: 'object', properties: { id: str }, required: ['id'] } },
  { name: 'add_text', description: "Add a text overlay. x/y are 0..1 of frame (0.5,0.5 = center); fontSize is px at 1080p and auto-shrinks so the text fits the frame. preset title | lower-third | caption | end-card supplies the lane, size, box and fades (anything you pass explicitly wins). Title, lower-third and end-card presets wear the active style theme (font, colours, outline) unless you pass font or color. Warns if it lands on top of another text, off-frame, or flashes too briefly.", inputSchema: { type: 'object', properties: { text: str, start: num, theme: { ...str, description: 'style this one text in a theme (id or words) instead of the active one' }, font: { ...str, enum: ['impact', 'headline', 'comic', 'tech', 'mono', 'terminal', 'serif', 'round', 'marker', 'heavy', 'clean', 'grotesk'], description: 'a theme font by role' }, at: { ...str, description: 'WORD ANCHOR: place it when these words are spoken instead of at a number, e.g. "arcade" or "end:arcade" (after/before pick between repeats)' }, preset: { ...str, enum: ['title', 'lower-third', 'caption', 'end-card'] }, duration: num, x: num, y: num, fontSize: num, color: str, fadeIn: num, fadeOut: num, box: bool, boxOpacity: num, after: num, before: num }, required: ['text'] } },
  { name: 'update_text', description: 'Patch a text overlay by textId. New words for a themed caption keep the spoken timing of the words that are still there, so the highlight stays on the voice.', inputSchema: { type: 'object', properties: { textId: str, text: str, start: num, duration: num, x: num, y: num, fontSize: num, color: str, font: { ...str, enum: ['impact', 'headline', 'comic', 'tech', 'mono', 'terminal', 'serif', 'round', 'marker', 'heavy', 'clean', 'grotesk'] }, outline: { ...num, description: 'outline width as a fraction of the font size, e.g. 0.08' }, outlineColor: str, box: bool, boxColor: str, boxOpacity: num }, required: ['textId'] } },
  { name: 'set_theme', description: "Set the video's STYLE THEME from what the creator said: an id or their own words. \"make it fun\", \"clean minimalism\", \"futuristic tech captions but green\", \"cartoon, bigger, at the top\" each land on a finished baseline (caption font, colours, motion such as highlight/pop/karaoke/typewriter/glow/glitch, title fonts, thumbnail text) with the tweak words applied on top. Restyles the captions and titles already on the timeline unless restyle:false. Returns the theme, the tweaks it understood, and its feel (transitions, music, sfx) to steer your other choices. Call with no theme to list them. Themes: creator, clean, hype, fun, cartoon, tech, terminal, cinematic, elegant, news, neon, handmade, karaoke, explainer, randotechnerd.", inputSchema: { type: 'object', properties: { theme: { ...str, description: 'theme id or the creator\'s words' }, restyle: { ...bool, description: 'restyle existing captions/titles, default true' }, titles: { ...bool, description: 'also restyle titles, default true' } } } },
  { name: 'make_captions', description: "Caption the whole timeline on-device (Whisper word timings) in the active style theme, or the theme you pass. Lines break at pauses and sentence ends and keep their word timings, so highlight/pop/karaoke/typewriter motions land on each spoken word. Replaces earlier themed captions unless replace:false. The export burns them with the same renderer VidHelm Cloud uses.", inputSchema: { type: 'object', properties: { theme: { ...str, description: 'theme id or words; omit to use the active theme' }, replace: bool } } },
  { name: 'add_tag', description: 'Drop a tag point (marker) at time t, or on a spoken word with at. Tags are the beat map of the video - SFX, narration and the score hits line up with them.', inputSchema: { type: 'object', properties: { t: num, at: { ...str, description: 'WORD ANCHOR: place it when these words are spoken instead of at a number, e.g. "arcade" or "end:arcade" (after/before pick between repeats)' }, label: str, after: num, before: num } } },
  { name: 'update_tag', description: 'Move or rename a tag by tagId.', inputSchema: { type: 'object', properties: { tagId: str, t: num, label: str }, required: ['tagId'] } },
  { name: 'list_sfx', description: 'List the sound-effect library (13 built-ins + user customs).', inputSchema: { type: 'object', properties: {} } },
  { name: 'place_sfx', description: 'Place a library sound effect on the SFX track at time t (defaults to the playhead) or on a spoken word with at. Try whoosh, pop, boing, squish, gummy-squish, gloop, poof, spoosh, sparkle, party, riser, ding, thud.', inputSchema: { type: 'object', properties: { name: str, t: num, at: { ...str, description: 'WORD ANCHOR: place it when these words are spoken instead of at a number, e.g. "arcade" or "end:arcade" (after/before pick between repeats)' }, volume: num, after: num, before: num }, required: ['name'] } },
  { name: 'transport', description: 'Move the playhead and/or start/stop playback in the app window.', inputSchema: { type: 'object', properties: { seek: { ...num, description: 'seconds' }, at: { ...str, description: 'WORD ANCHOR: place it when these words are spoken instead of at a number, e.g. "arcade" or "end:arcade" (after/before pick between repeats)' }, play: bool } } },
  { name: 'set_format', description: 'Set export format: orientation landscape|portrait|square, resolution 4K|1440p|1080p|720p, fps 24|30|60. Any other value is refused with an error and nothing changes. Returns the format actually set (with its width and height).', inputSchema: { type: 'object', properties: { orientation: { ...str, enum: ['landscape', 'portrait', 'square'] }, resolution: { ...str, enum: ['4K', '1440p', '1080p', '720p'] }, fps: { ...num, description: 'frames per second: 24, 30 or 60' } } } },
  { name: 'export_video', description: 'Render the timeline to an mp4 at outputPath (absolute). Blocks until done; returns the automatic quality-check verdict (loudness, peaks, black frames).', inputSchema: { type: 'object', properties: { outputPath: str, qualityCheck: bool }, required: ['outputPath'] } },
  { name: 'open_panel', description: 'Open/close a panel in the app for the user: booth (karaoke recorder), narration (cloned voice), sfx (sound library tab), media (bin tab), settings, thumbnail (frame picker), connect (AI connection setup + troubleshooter), help (first-run tour, credits and licences), model3d (3D Studio, pass path to load an STL/3MF/OBJ for the user to pose and render as a turntable clip).', inputSchema: { type: 'object', properties: { panel: { ...str, enum: ['booth', 'narration', 'sfx', 'media', 'settings', 'thumbnail', 'connect', 'model3d', 'help', 'takes'] }, open: bool, path: { ...str, description: 'model3d only: absolute path to a .stl/.3mf/.obj to load' } }, required: ['panel'] } },
  { name: 'render_3d', description: "Render the model currently open in the 3D Studio (open_panel model3d first). Returns a clip in the media bin: a spinning turntable, or a still. transparent:true renders with no backdrop and drops it on the video track AT THE PLAYHEAD so it composites on top of the footage underneath, that is how you put a spinning print over a video. Blocks for roughly `seconds` while it records.", inputSchema: { type: 'object', properties: { seconds: { ...num, description: 'turntable length, 1-30 (default 6)' }, transparent: { ...bool, description: 'no backdrop; becomes an overlay on top of the footage' }, still: { ...bool, description: 'true = single frame instead of a spin' } } } },
  { name: 'prepare_analysis', description: "Get the current work into a shape a video-analysis service (Adversal's process_video, or similar) can take, and find out what still needs looking at. scope 'timeline' flattens the whole timeline to a small mp4 whose timestamps match the timeline exactly; scope 'clip' skips rendering and hands back the original file with in/out points. Either way you get `gaps`, the stretches with no tag point within gapPad seconds: analyse only those on a second pass so already-marked material is not re-examined, and add tags at (returned timestamp + toTimeline.add).", inputSchema: { type: 'object', properties: { scope: { ...str, enum: ['timeline', 'clip'], description: "default 'timeline'" }, clipId: { ...str, description: 'clip scope: which clip, defaults to the first video clip' }, gapPad: { ...num, description: 'seconds either side of a tag counted as already covered (default 10)' }, minGap: { ...num, description: 'ignore gaps shorter than this (default 5)' }, outputPath: { ...str, description: 'timeline scope: where to write the flattened mp4' } } } },
  { name: 'open_project', description: "The human can point VidHelm at a project folder whose sub-folders are projects, each holding its own footage. Call with no arguments to list them (and see which is open); pass name to open one, which loads that folder's media into the bin and restores any saved timeline. Opening replaces the timeline, so while get_state says unsaved it refuses: ask the human, then call again with save:true (save, then open) or force:true (discard the changes). It also refuses, opening nothing, when the target project holds unsaved work from an earlier session: only the human can restore or discard that, so ask them to choose the project in the Media panel's project list, then carry on. Errors if no project folder is configured.", inputSchema: { type: 'object', properties: { name: { ...str, description: 'project (sub-folder) name; omit to just list' }, save: { ...bool, description: 'save the current unsaved changes first, then open (ask the human first)' }, force: { ...bool, description: 'open it and DISCARD the current unsaved changes (ask the human first)' } } } },
  { name: 'set_booth_script', description: "Put a read-along script into the karaoke booth and open it (one line per beat; lines pin to the user's tag points). Use after analyzing footage, e.g. from a transcript, your own writing, or video-analysis notes, so the user can re-record clean narration in one take.", inputSchema: { type: 'object', properties: { script: { ...str, description: 'the lines, newline-separated' }, open: bool }, required: ['script'] } },
  { name: 'cut_pauses', description: 'Detect and remove dead space (silent pauses, or motionless stretches for silent footage) across the whole timeline, splicing seamlessly with short crossfades. Uses the thresholds from Settings. Undoable.', inputSchema: { type: 'object', properties: {} } },
  { name: 'find_repeats', description: "Read the timeline's speech on-device and find the spots where the same line was said more than once (retakes, false starts). Returns each group with every attempt's words, timing, and which one is picked by default (longest, finished, fewest fillers, later on a tie). Cuts nothing: it opens the Takes & history panel so the human sees the same list. Follow with apply_takes.", inputSchema: { type: 'object', properties: {} } },
  { name: 'apply_takes', description: "Cut the rejected takes found by find_repeats out of the timeline, rippling the rest left. Pass keep to overrule which attempt survives, and drop for extra transcript lines to cut (a flub with no retake). Undoable with the app's own undo. Re-running with different choices re-cuts from the pre-cut state as long as the human has not edited the timeline since.", inputSchema: { type: 'object', properties: { keep: { ...str, description: 'per-group choice as group:member pairs using find_repeats indexes, e.g. "0:2, 1:0". Omit to use the defaults it picked.' }, drop: { ...str, description: 'extra transcript line indexes to cut, e.g. "4, 9"' } } } },
  { name: 'run_recipe', description: "Run the user's Start Recipe (their standing workflow, shown in get_state.startRecipe), executes the app-native steps (cut-pauses, intro-audio, logo, thumbnail picker) and reports which steps are yours to do (titles, subtitle...).", inputSchema: { type: 'object', properties: {} } },
  { name: 'sample_frames', description: 'Sample N frames from the first timeline video (or an explicit path), returns times + jpg paths for choosing a thumbnail moment. rank:true samples ~3x as many and returns the best REAL frames first (sharp, well exposed, colourful, a person in shot, near-duplicates dropped), each with a short why. Look at them before picking.', inputSchema: { type: 'object', properties: { count: num, path: str, rank: bool } } },
  { name: 'compose_thumbnail', description: "Compose a 1280x720 YouTube thumbnail in the style theme. Picture, in order: imagePath (the creator's own photo), else a photo in the project named like thumb/cover/photo, else the video frame at t, else (no t) the best-ranked real frame, else a PLACEHOLDER card. Text bottom-left: 'BIG HOOK | smaller second line' (second line in the accent colour); brand logo top-right automatically. If the reply has tellTheCreator, relay it: a real photo beats a frame or AI art.", inputSchema: { type: 'object', properties: { t: num, imagePath: { ...str, description: 'absolute path to the creator\'s photo' }, subtitle: str, outPath: str, path: str, theme: { ...str, description: 'theme id or words; default the active theme' }, placeholder: { ...bool, description: 'force a placeholder card' } }, required: ['outPath'] } },
  { name: 'scan_broll', description: "Look through a folder of b-roll and measure every clip: length, sound, the steady part worth using, and a CONTACT SHEET image per clip. Defaults to the `broll` sub-folder of the open project. You then open each sheet, see what is in it, and call label_broll: those labels are the only thing plan_broll can match against, so unlabelled footage is never used. Labels are remembered in the folder itself (.vidhelm-broll.json), so a re-scan keeps them.", inputSchema: { type: 'object', properties: { folder: { ...str, description: 'absolute path; defaults to <project>/broll' }, refresh: { ...bool, description: 're-measure and rebuild contact sheets even if they exist' } } } },
  { name: 'label_broll', description: "Say what is in one b-roll clip, after looking at its contact sheet. Short concrete nouns work best ('coffee beans', 'grinder', 'pouring', 'portafilter'): they are matched against the words actually spoken. Optionally narrow the usable part with bestStart/bestEnd, or cap how often it may appear with maxUses.", inputSchema: { type: 'object', properties: { id: { ...str, description: 'the file name from scan_broll' }, labels: { ...str, description: 'comma-separated, e.g. "coffee beans, pouring, close up"' }, description: { ...str, description: 'one sentence about the shot' }, bestStart: num, bestEnd: num, maxUses: num, folder: str }, required: ['id'] } },
  { name: 'plan_broll', description: "Work out which cutaway goes over which line, WITHOUT touching the timeline. Reads the timeline's speech word by word, splits it into sentences, and matches labelled b-roll to what is being said. A cutaway only ever covers a whole sentence, never starts in the opening seconds, keeps its distance from the next one, and is capped as a share of the runtime, so the video does not turn into a slideshow. Returns what it would do and why; place_broll commits it.", inputSchema: { type: 'object', properties: { minDuration: { ...num, description: 'shortest cutaway, default 1.4s' }, maxDuration: { ...num, description: 'longest cutaway, default 5s' }, gapBetween: { ...num, description: 'seconds back on camera between cutaways, default 4' }, coverage: { ...num, description: 'most of the runtime that may be b-roll, 0-1, default 0.35' }, protectStart: { ...num, description: 'leave this many opening seconds alone, default 8' }, minScore: { ...num, description: 'how good a match must be, 0-1, default 0.34' }, protect: { ...str, description: 'stretches that must stay on camera, as "start-end" seconds: "0-12, 300-330"' }, model: { ...str, description: "whisper model: tiny, base or small. Default small (slower, more accurate)" } } } },
  { name: 'place_broll', description: "Put the planned cutaways on the timeline's B-ROLL track. Picture only: the audio underneath keeps playing straight through, and each cutaway ends on a word boundary so the picture comes back cleanly. Pass drop to leave some out.", inputSchema: { type: 'object', properties: { drop: { ...str, description: 'plan indexes to skip, e.g. "0, 3"' } } } },
  { name: 'analyze_speech', description: "Read every word on the timeline with its timing, and split it into sentences. This is the pass that find_phrase, cut_at_phrase and plan_broll all measure from; it is cached until the timeline changes. Defaults to the `small` Whisper model because accuracy matters more here than speed (first use downloads it once).", inputSchema: { type: 'object', properties: { model: { ...str, description: 'tiny, base or small (default small)' }, refresh: { ...bool, description: 'ignore the cache and read it again' } } } },
  { name: 'find_phrase', description: "Find where a line was said and get exact in/out points for it, without cutting anything. Tolerant of transcription slips. Crucially it TRIMS WHAT DANGLES: ask for 'check out this portable espresso maker' when the recording runs on into 'and this...' and the out point lands after 'maker', not after 'this'. The point is then snapped to the real waveform so no consonant is clipped and no dead air is left.", inputSchema: { type: 'object', properties: { text: { ...str, description: 'roughly what was said' }, after: { ...num, description: 'only look after this time, for a line said more than once' }, before: num, refine: { ...bool, description: 'set false to skip waveform snapping' }, model: str }, required: ['text'] } },
  { name: 'cut_at_phrase', description: "Cut the timeline at a spoken phrase, precisely. mode 'end' (default) drops everything after the phrase, 'start' drops everything before it, 'split' only cuts the clips there and removes nothing. Same dangling-clause trimming as find_phrase, so 'cut after the fine grind line' does not leave half of the next sentence attached.", inputSchema: { type: 'object', properties: { text: { ...str, description: 'roughly what was said' }, mode: { ...str, enum: ['end', 'start', 'split'] }, after: num, before: num, refine: bool, model: str }, required: ['text'] } },
  { name: 'plan_framing', description: "Work out where a 9:16 crop should point, measured from the footage rather than guessed: decodes the clip and finds the subject per shot, then HOLDS the crop still inside a shot unless the subject really moves, and limits how fast it may travel. Returns one entry per steady hold plus a ready-made ffmpeg crop expression. Pass hints if you have looked at frames yourself and know where the subject is.", inputSchema: { type: 'object', properties: { path: { ...str, description: 'defaults to the first timeline video' }, sourceStart: num, duration: num, fps: { ...num, description: 'analysis sample rate, default 4' }, aspect: { ...num, description: 'target aspect, default 0.5625 (9:16)' }, hints: { ...str, description: 'subject positions you can see yourself, as "time@x" with x 0-1 across the frame: "3@0.72, 9.5@0.35"' } } } },
  { name: 'set_recipe', description: "Change the user's Start Recipe (their standing workflow) and have it persist. mode 'append' (default) adds lines at the end, 'prepend' at the top, 'replace' swaps the lot, 'show' just returns it. Always go through this rather than editing the settings file: the running app owns that file and rewrites it from memory whenever anything changes, so an outside edit looks like it worked and then quietly disappears.", inputSchema: { type: 'object', properties: { text: { ...str, description: 'the lines to add' }, mode: { ...str, enum: ['append', 'prepend', 'replace', 'show'] } } } },
  { name: 'search_sfx', description: "Search free sound-effect libraries and get results with their LICENCES. Wikimedia Commons is always searched (no key needed); Freesound is searched too when the user has pasted a free token in Settings, and it is far bigger and better tagged. Non-commercial and unlicensed sounds are hidden by default, because they are not safe on a monetised channel. Results are ranked, and each says whether it needs crediting.", inputSchema: { type: 'object', properties: { query: { ...str, description: 'what the sound is, e.g. "coffee beans pour" or "electronic door"' }, limit: num, maxSeconds: { ...num, description: 'default 15, keeps music out' }, safeOnly: { ...bool, description: 'set false to also see non-commercial and unlicensed results' } }, required: ['query'] } },
  { name: 'download_sfx', description: "Save one search result into the user's own sound folder so it can be placed on the timeline. Anything that needs crediting is also written into CREDITS.txt beside the file, and the credit line comes back so it can go in the video description.", inputSchema: { type: 'object', properties: { index: { ...num, description: 'which result from the last search_sfx, starting at 0' } } } },
  { name: 'make_score', description: "Compose an original music bed that is SYNCED to the edit: the tempo is fitted to the existing cuts, a stereo whoosh rides every cut, every tag point gets an impact with the music ducked underneath it, fast-cut bars play denser, the arrangement calms down after the last tag, and the tail past the final cut sits on a drone. Two palettes: electronic (kick, clap, hats, arp riff) or cinematic (bowed strings, cello ostinato, felt piano, taiko, choir, braams, a riser into every hit and a POCKET OF SILENCE before each drop). Fully synthesized, nothing to license. Tag the moments that matter first (add_tag), snap_to_grid if you want the hits exact, then call this; re-run after re-editing since the score is derived from the cuts. Placed on a1 unless place:false.", inputSchema: { type: 'object', properties: { style: { ...str, enum: ['electronic', 'cinematic'], description: 'palette, default electronic' }, intensity: { ...str, description: 'chill, standard or epic' }, bpm: { ...num, description: 'override the fitted tempo' }, seed: { ...num, description: 'change it for a different take' }, name: { ...str, description: 'library name for the wav' }, place: { ...bool, description: 'false = render to the library only' }, volume: { ...num, description: 'clip gain when placed, default 1' } } } },
  { name: 'make_sfx', description: "Synthesize a sound effect from a physical model rather than downloading one: coffee beans poured into a hopper (metal, plastic or glass), a sci-fi door opening or closing, a podracer starting, and one flying past with real Doppler. Call with no recipe to list them. A different seed gives another take of the same sound, and intensity changes how much of it there is.", inputSchema: { type: 'object', properties: { recipe: { ...str, description: 'coffee-beans, coffee-beans-plastic, coffee-beans-glass, door-electronic, door-electronic-close, podracer-start, podracer-pass' }, seed: { ...num, description: 'change it for a different take' }, intensity: { ...num, description: '0-1' }, duration: num } } },
  { name: 'find_word', description: "Where was a word or short phrase SAID? Returns every occurrence with its start and end from the transcript, so you can hang text, SFX, tags or cuts on the moment a word lands (the whole trick behind a tight teaser). Then pass at:\"<words>\" (or at:\"end:<words>\") to add_text, add_tag, place_sfx, split_clip, add_clip or transport instead of a number.", inputSchema: { type: 'object', properties: { text: { ...str, description: 'the word or phrase, roughly' }, after: num, before: num, model: str }, required: ['text'] } },
  { name: 'snap_to_grid', description: "Quantise the edit to a musical grid so hits land EXACTLY: every join between picture clips is rolled onto the nearest beat (the cut moves, nothing downstream shifts, runtime unchanged) and every tag point slides onto the nearest bar line. bpm defaults to the tempo fitted to the cuts; call make_score with the same bpm afterwards. Nothing moves further than tolerance, and a roll that would starve a clip or run off its source is skipped and reported. dryRun shows the moves without applying them.", inputSchema: { type: 'object', properties: { bpm: num, phase: { ...num, description: 'grid origin in seconds, default the first picture clip' }, cutDivision: { ...str, enum: ['bar', 'half', 'beat'], description: 'default beat' }, tagDivision: { ...str, enum: ['bar', 'half', 'beat'], description: 'default bar' }, tolerance: { ...num, description: 'max seconds a cut may move, default half a step' }, tagTolerance: num, snapCuts: bool, snapTags: bool, dryRun: bool } } },
  { name: 'capture_site', description: "Capture a website, web app or localhost dev server as footage, rendered by the app's own Chromium at an exact size and theme: a still PNG, or (with seconds) a real-time screen recording mp4. script runs in the page first, so you can seed state, open a panel, freeze animations or patch CSS before the shot. The result lands in the media bin and on the video track unless place:false. This is how product videos get their UI shots.", inputSchema: { type: 'object', properties: { url: str, width: { ...num, description: 'default 1920' }, height: { ...num, description: 'default 1080' }, theme: { ...str, enum: ['light', 'dark'] }, script: { ...str, description: 'JavaScript to run in the page before capturing' }, settle: { ...num, description: 'ms to wait after load/script, default 800' }, seconds: { ...num, description: 'record this long instead of a still (max 120)' }, fps: { ...num, description: 'recording rate, default 30' }, duration: { ...num, description: 'how long a still stays on the timeline, default 5' }, start: num, place: bool, outPath: str }, required: ['url'] } },
  { name: 'look_through', description: "Actually SEE the video: samples it end to end and returns contact sheets with the TIMECODE BURNED INTO EVERY TILE, so anything you notice can be quoted with the second it happened. This is how you read a display, a label or a product name, spot what is on screen at a moment, or find the shot worth cutting to. Long videos widen the interval rather than covering only the beginning. Pair it with analyze_speech to line up what was seen with what was said.", inputSchema: { type: 'object', properties: { path: { ...str, description: 'defaults to the first timeline video' }, interval: { ...num, description: 'seconds between frames, default 8' }, maxFrames: { ...num, description: 'cap, default 120; the interval widens to stay under it' }, perSheet: { ...num, description: 'tiles per sheet, default 9' }, tileWidth: { ...num, description: 'pixels per tile, default 640; raise it to read small text' }, sourceStart: { ...num, description: 'add this to every reported timecode' } } } },
  { name: 'generate_clip', description: "Generate a VIDEO clip with AI and put it in the bin (and at the end of v1): a shot from a description, one picture brought to life, or a transition that morphs one picture into another (from + to). `from` is a bin media name/id, a file path, or 'playhead' for the frame under the playhead (with `at` as an override time); `to` is an image. Landscape 5-10 s. Needs the human's fal.ai key (✨ AI clip panel). Costs real money (~$0.35-0.75 per 5 s), so use it when footage cannot give the shot. Blocks until the clip is in (usually 1-4 min, at most about 12). NEVER retry after a timeout or a reply with stillRunning: the generation is still going and a retry pays again. Check get_state's mediaBin for the ai-clip first.", inputSchema: { type: 'object', properties: { prompt: { ...str, description: 'subject, camera move, light, mood' }, from: { ...str, description: "media name/id, path, or 'playhead'" }, at: { ...num, description: 'source time for a video `from`' }, to: { ...str, description: 'image media name/id or path: the last frame' }, seconds: { ...num, description: '5, 8 or 10' }, model: { ...str, description: 'kling-2.1 | kling-2.5 | luma-ray2 | hailuo-02 | veo-3.1 | veo-3.1-fal (optional)' }, place: { type: 'boolean', description: 'false = bin only' } } } },
]

async function runTool(name, args = {}) {
  switch (name) {
    case 'get_state': return call('GET', '/state')
    case 'screenshot': {
      const r = await call('GET', '/screenshot')
      if (r.png) return { __image: r.png.toString('base64') }
      return r
    }
    case 'transport': {
      const out = {}
      if (typeof args.at === 'string') Object.assign(out, await call('POST', '/command', { action: 'seek', at: args.at }))
      else if (typeof args.seek === 'number') Object.assign(out, await call('POST', '/command', { action: 'seek', t: args.seek }))
      if (typeof args.play === 'boolean') Object.assign(out, await call('POST', '/command', { action: 'play', playing: args.play }))
      return Object.keys(out).length ? out : { error: 'pass seek and/or play' }
    }
    case 'export_video': return call('POST', '/command', { action: 'export', ...args })
    case 'open_panel': return call('POST', '/command', { action: 'ui', ...args })
    case 'cut_pauses': return call('POST', '/command', { action: 'cut_pauses' })
    case 'find_repeats': return call('POST', '/command', { action: 'find_repeats' })
    case 'apply_takes': return call('POST', '/command', { action: 'apply_takes', ...args })
    case 'run_recipe': return call('POST', '/command', { action: 'run_recipe' })
    case 'sample_frames': return call('POST', '/command', { action: 'sample_frames', ...args })
    case 'compose_thumbnail': return call('POST', '/command', { action: 'compose_thumbnail', ...args })
    case 'prepare_analysis': return call('POST', '/command', { action: 'prepare_analysis', ...args })
    case 'open_project': return call('POST', '/command', { action: 'open_project', ...args })
    case 'set_booth_script': return call('POST', '/command', { action: 'booth_script', ...args })
    case 'render_3d': return call('POST', '/command', { action: 'render_3d', ...args })
    case 'look_through': case 'find_word': case 'snap_to_grid': case 'capture_site':
    case 'search_sfx': case 'download_sfx': case 'make_sfx': case 'make_score':
    case 'set_recipe': case 'generate_clip': case 'set_theme': case 'make_captions':
    case 'scan_broll': case 'label_broll': case 'plan_broll': case 'place_broll':
    case 'analyze_speech': case 'find_phrase': case 'cut_at_phrase': case 'plan_framing':
      return call('POST', '/command', { action: name, ...args })
    case 'add_media': case 'add_clip': case 'update_clip': case 'split_clip': case 'delete_item':
    case 'add_text': case 'update_text': case 'add_tag': case 'update_tag': case 'list_sfx':
    case 'place_sfx': case 'set_format':
      return call('POST', '/command', { action: name, ...args })
    default: return { error: `unknown tool ${name}` }
  }
}

// ---- MCP stdio plumbing ----
const send = (msg) => process.stdout.write(JSON.stringify(msg) + '\n')
const rl = readline.createInterface({ input: process.stdin })
rl.on('line', async (line) => {
  line = line.trim()
  if (!line) return
  let req
  try { req = JSON.parse(line) } catch { return }
  const { id, method, params } = req
  if (method === 'initialize') {
    return send({ jsonrpc: '2.0', id, result: { protocolVersion: params?.protocolVersion || '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'vidhelm', version: '1.9.0' }, instructions: INSTRUCTIONS } })
  }
  if (method === 'notifications/initialized' || method?.startsWith('notifications/')) return
  if (method === 'ping') return send({ jsonrpc: '2.0', id, result: {} })
  if (method === 'tools/list') return send({ jsonrpc: '2.0', id, result: { tools: TOOLS } })
  // Empty (not method-not-found) so strict clients that probe these at startup
  // (LM Studio, Jan, some IDE integrations) don't log errors or bail.
  if (method === 'resources/list') return send({ jsonrpc: '2.0', id, result: { resources: [] } })
  if (method === 'resources/templates/list') return send({ jsonrpc: '2.0', id, result: { resourceTemplates: [] } })
  if (method === 'prompts/list') return send({ jsonrpc: '2.0', id, result: { prompts: [] } })
  if (method === 'tools/call') {
    const { name, arguments: args } = params || {}
    const result = await runTool(name, args)
    if (result?.__image) return send({ jsonrpc: '2.0', id, result: { content: [{ type: 'image', data: result.__image, mimeType: 'image/png' }] } })
    const isError = !!result?.error
    return send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: JSON.stringify(result, null, 1) }], isError } })
  }
  if (id !== undefined) send({ jsonrpc: '2.0', id, error: { code: -32601, message: `method not found: ${method}` } })
})
